services:
  nvd_mirror:
    image: msusel/nvd-mirror:latest
    container_name: nvd_mirror
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nvd_mirror
    networks:
      docker_postgres_network:
        aliases:
          - postgres_network

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      docker_postgres_network:
        aliases:
          - postgres_network

volumes:
  postgres_data:

networks:
  docker_postgres_network:
    driver: bridge
